language: python

python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2

install:
  - pip install --use-mirrors nose numpy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install --use-mirrors PIL; fi
  - python setup.py install

script:
  - mkdir ../foo
  - cd ../foo
  - if python ../matplotlib/tests.py ; then echo 'Success'; else tar cj `find . -name *-failed-diff.* | sed 's/-failed-diff//'` |  base64; fi;
